### PR TITLE
fixes mac.binary subtype handling accross insert/archive/prune functions

### LINKED ISSUE #88: write_PACKAGES and archive/pruneRepo work on different paths for mac.binary
Hi,

I encountered the following situation:

- `drat::insertPackage("package_0.2.11.tgz","~/repo")` works
- `drat::insertPackage("package_0.2.12.tgz","~/repo", action="archive")` reports the following error
```
Error in order(NULL, integer(0), na.last = TRUE, decreasing = TRUE, method = "auto") : 
  argument 1 is not a vector
```

This originates in `pruneRepo` via `archiveRepo`. The reason for this is that, the package binary gets written to `bin/macosx/el-capitan/contrib/3.6/`, but the pruning is trying to work on `bin/macosx/contrib/3.6`.

Before preparing a PR, I think this needs to be discussed, for me to understand the differences, since I am new to the inner workings of the repo structure R expects.

My initial starting question was: Why was the wheel reinvented using the the function `getPathForPackage` in `insertPackage`, when `contrib.url` is already available and used in `pruneRepo`?

https://github.com/eddelbuettel/drat/blob/12e03ee2f3ee70264e26c54ae25952616e6cff95/R/insertPackage.R#L97

and the next line could also be written as `contrib.url(repodir, type = pkgtype)` and probably solve the issue. Answer: The `el-capitan` subdir is there for a reason. 

So the real starting question is: For what reason is the `el-capitan` subdir required and when does R expects it to be present?

Thanks for any advice and hints in advance.

<details>
<summary>SessionInfo</summary>
<pre>
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] drat_0.1.5

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3  
</pre>
</details>

### PR DESCRIPTION
**Pull request by FelixErnst**
Fixes #88

### CODE REVIEW

File: DESCRIPTION [hunk 1]
```diff
@@ -1,11 +1,11 @@
 Package: drat
 Type: Package
 Title: 'Drat' R Archive Template
-Version: 0.1.5
-Date: 2019-03-28
+Version: 0.1.6
```
Comment (eddelbuettel) [inline DESCRIPTION:4]: It's minor but I tend to set those as these "final" numbers only when I prepare the release, so I would have called this 0.1.5.1 instead.

File: R/archivePackages.R [hunk 2]
```diff
@@ -22,8 +24,8 @@
 archivePackages <- function(repopath = getOption("dratRepo", "~/git/drat"),
                             type = "source", 
                             pkg) {
-   
-    ## TODO need to deal with binary repos...
+    
+    ## knows how to handle binary repos
```
Comment (eddelbuettel) [inline R/archivePackages.R:28]: :-)

File: R/insertPackage.R [hunk 3]
```diff
@@ -111,7 +109,11 @@ insertPackage <- function(file,
     }
 
     ## update index
-    write_PACKAGES(pkgdir, type = pkgtype, ...)
+    split_pkgtype <- strsplit(pkgtype,"\\.")[[1L]]
+    write_pkgtype <- 
+        paste(split_pkgtype[seq.int(1L,min(2L,length(split_pkgtype)))],
+              collapse = ".")
```
Comment (eddelbuettel) [inline R/insertPackage.R:115]: That is excessive indentation which, to me, prohibits readability.  100 columns are fine, most of us have wide-screen monitors.

File: DESCRIPTION (hunk 1 above)
Comment (FelixErnst) [reply DESCRIPTION]: Changed this to 0.1.5.1. I am quite keen to get it to CRAN, since I tripped over this this morning. It would save me some time by not having to prepare a preliminary solution

File: R/insertPackage.R (hunk 3 above)
Comment (FelixErnst) [reply R/insertPackage.R]: Thanks have to go to Bioconductor's BiocCheck. I didn't even notice it ...

File: DESCRIPTION (hunk 1 above)
Comment (eddelbuettel) [reply DESCRIPTION]: I can probably help with that especially if you can help with testing (i.e. I have no macOS binaries hanging around)

Comment (FelixErnst) [reply DESCRIPTION]: Sure thing. I did all the testing on macOS `Catalina` and thats how I noticed the problem. The code in the PR works for R `3.6` and `4.0`. I inserted packages, archived and pruned.

Do you have other test in mind?

Comment (eddelbuettel) [reply DESCRIPTION]: The macOS case is, I think,  by far the most complicated.

File: R/insertPackage.R [hunk 4]
```diff
@@ -220,41 +245,20 @@ getPackageInfo <- function(file) {
...
+        return(contrib_url)
     }
-    return(ret)
+    version <- as.character(version)
+    split_version <- strsplit(version,"\\.")[[1L]]
+    if(length(split_version) < 2L || length(split_version) > 3L){
+        stop("'version' must be in the format 'X.Y' or 'X.Y.Z'.")
+    }
+    version <- paste(split_version[seq.int(1L,min(2L,length(split_version)))],
+                     collapse = ".")
```
Comment (nfultz) [inline R/insertPackage.R:259]: If you convert version to a `base::package_version()` instead of `as.character`, you can replace all the string munging with

    paste0(version$major, '.', version$minor)

Comment (FelixErnst) [reply R/insertPackage.R:259]: I thought about this, but there is no base R function I could find, which reports `version$minor` as `6` (for R `3.6`). Therefore the default output is `getRversion()`, which returns `3.6.3` a special class, which is not `character` and thus has to be converted.

Comment (eddelbuettel) [reply R/insertPackage.R:259]: I missed that. I use that a lot too (somewhere even from `configure`.  That S3 class `package_version` and its constructors, and added operators, is gold.  Hidden jewel.

Comment (FelixErnst) [reply R/insertPackage.R:259]: I am happy to change that, if there is a function, which reports `3.6` or `4.0` and not `3.6.3` or `4.0.0`

Comment (FelixErnst) [reply R/insertPackage.R:259]: Ok, now I got it. Give me a moment

Comment (nfultz) [reply R/insertPackage.R:259]: I was thinking something like this:

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] colorout_1.2-2

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3   
> version <- getRversion()
> version$minor
[1] 6
> paste0(version$major, '.', version$minor)
[1] "3.6"

```

Comment (FelixErnst) [reply R/insertPackage.R]: done. I didn't realize, that there are these accessor, even though there are referenced in the examples.

Thanks for the checking that.

Comment (eddelbuettel) [reply R/insertPackage.R]: Yes, high redundancy.  getRversion() and alike give us the components.  The S3 class gives us comparison.

File: DESCRIPTION (hunk 1 above)
Comment (mbjones) [reply DESCRIPTION]: @eddelbuettel I took a quick look at the proposed changes and agree they seem to improve the state of things. The original function was intended to address problems we encountered with MacOS, and it seems we missed some key functionality. So I'm all in support of fixing these issues while retaining the ability to install and upgrade mac packages from the CRAN-sanctioned locations. Thanks for reaching out.

**Comment by eddelbuettel** [comment]
Thanks everybody for the feedback.  This is looking promising enough, as do casual tests on the checked out PR branch.  As @FelixErnst did some serious enough polishing and expressed a need for seeing this fixed -- coupled with the [good standing at CRAN](https://cloud.r-project.org/web/checks/check_results_drat.html) I think I will merge, roll it up as 0.1.6 and ship it.

**Comment by eddelbuettel** [comment]
And now on CRAN -- thanks _so much_ everybody for help and input, and especially to @FelixErnst for a patiently revised PR.  Let's hope it does the trick for you mac heads; if need be we can always refine once more.

**Comment by FelixErnst** [comment]
Thanks for the quick and helpful comments @eddelbuettel @nfultz and for the push to CRAN.

I will continue to keep an eye on this, since I have to supply packages to mac users.
